# The URL the site will be built for
base_url = "https://jslazak.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "terminimal"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo_text = "@j-g00da's webpage"
author = "Jagoda Ślązak"
accent_color = "orange"
background_color = "dark"
enable_post_view_navigation = true
default_language = "en"

menu_items = [
    {name = "blog", url = "$BASE_URL"},
#    {name = "projects", url = "$BASE_URL/projects"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "github", url = "https://github.com/j-g00da", newtab = true},
    {name = "fosstodon", url = "https://fosstodon.org/@j_g00da", newtab = true},
    {name = "bluesky", url = "https://bsky.app/profile/jgda.bsky.social", newtab = true},
    {name = "linkedin", url = "https://www.linkedin.com/in/jagoda-ślązak-7a6a90274/", newtab = true},
]
